-- MySQL Script generated by MySQL Workbench
-- 05/14/15 18:18:22
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema project_genesis
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema project_genesis
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `project_genesis` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `project_genesis` ;

-- -----------------------------------------------------
-- Table `project_genesis`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `project_genesis`.`user` ;

CREATE TABLE IF NOT EXISTS `project_genesis`.`user` (
  `user_id` INT NOT NULL AUTO_INCREMENT,
  `pseudo` VARCHAR(20) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `permission` VARCHAR(45) NOT NULL,
  `isConnected` TINYINT(1) NOT NULL DEFAULT 0,
  `last_connection` TIMESTAMP NULL,
  PRIMARY KEY (`user_id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
